upgrade package version
masalabs/MASA.EShop pull request #11
Opened 2023-04-27 12:32 UTC by MapleWithoutWords

2023-04-28 06:42 UTC, doddgu commented
@zhenlei520 PTAL

2023-05-09 03:28 UTC, zhenlei520 requested changes

2023-05-09 03:28 UTC, zhenlei520 commented on Directory.Build.props
> +    <MasaUtilsPackageVersion>1.0.0-rc.1</MasaUtilsPackageVersion>
It is recommended to use the same parameter to control the MASA Framework version

2023-05-09 03:28 UTC, zhenlei520 commented on src/Api/Masa.EShop.Api.Open/Callers/Ordering/OrderingCaller.cs
> +        Prefix = "/api/v1/orders/";
It is more recommended to use the overload to change the prefix

```csharp 
protected override string Prefix { get; set; } = "/api/v1/orders/";
```

2023-05-09 03:28 UTC, zhenlei520 commented on src/Services/Masa.EShop.Services.Catalog/Program.cs
>                 .UseEventBus()
Delete line:8, and modify

```csharp
.UseEventBus(eventBuilder => eventBuilder.UseMiddleware(typeof(ValidatorMiddleware<>))
```

> They have the same effect and are only recommended

2023-05-09 03:28 UTC, zhenlei520 commented on src/Services/Masa.EShop.Services.Catalog/_Imports.cs
> +global using Masa.BuildingBlocks.Data.UoW;
Use global sort

2023-05-09 03:28 UTC, zhenlei520 commented on src/Services/Masa.EShop.Services.Payment/_Imports.cs
> +global using Masa.Contrib.Ddd.Domain.Repository.EFCore;
Use global using sort

2023-05-10 02:17 UTC, zhenlei520 requested changes

2023-05-10 02:17 UTC, zhenlei520 commented on src/Services/Masa.EShop.Services.Catalog/Program.cs
> +               .UseEventBus(eventBusBuilder=>eventBusBuilder.UseMiddleware(typeof(ValidatorMiddleware<>)))
format code

2023-05-10 03:00 UTC, zhenlei520 approved these changes
LGTM @MayueCif

2023-05-10 03:01 UTC, MayueCif approved these changes

2023-05-10 03:01 UTC, merged